### ISSUE TITLE
[Cadastro de Imóvel] CNPJ pedindo Data de Nascimento

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#102]
Na tela de cadastro de imóvel, ao tentar adicionar um proprietário o sistema não difere CPF de CNPJ e pede Data de Nascimento quando informamos um CNPJ.

![CleanShot 2023-01-22 at 15 19 18@2x](https://user-images.githubusercontent.com/13375294/213933089-3593ea81-08de-4f84-81b2-193ebcd561a6.png)

**Comment by renatoSouzaAlmeida** [comment]
Problema resolvido
