### ISSUE TITLE
[Cadastro de Unidades] Label do tipo está errada

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#103]
Quando estamos no passo de cadastro da unidade, o nome da label está tipo de Imovel, quando deveria ser tipo da unidade. A validação do campo está com o texto correto.

![CleanShot 2023-01-22 at 15 25 24@2x](https://user-images.githubusercontent.com/13375294/213933213-f2a0dcd3-33c0-4ab2-8385-45f650372d59.png)

**Comment by renatoSouzaAlmeida** [comment]
Ajuste publicado em produção 
https://github.com/cBarbosa/iris-gestao/pull/108

**Comment by renatoSouzaAlmeida** [comment]
Ajuste realizado, menu de conratos removido

**Comment by renatoSouzaAlmeida** [comment]
Ajuste realizado, menu de conratos removido
