### ISSUE TITLE
[Cadastro de Cliente] Data de Nascimento

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#104]
A data está sendo preenchida no cadastro e na edição, mas não está sendo cadastrada.

![CleanShot 2023-01-22 at 16 40 13@2x](https://user-images.githubusercontent.com/13375294/213936601-2a6e2b1f-6df2-4490-96de-22a660bedd78.png)

**Comment by renatoSouzaAlmeida** [comment]
Problema resolvido
