### ISSUE TITLE
[Cadastro de Imóvel] Não está validando CPF nem CNPJ

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#105]
No cadastro de novo imovel, ao cadastrar um novo proprietario, não está validando o CPF nem o CNPJ.

![CleanShot 2023-01-22 at 16 43 11@2x](https://user-images.githubusercontent.com/13375294/213936749-bfad2c65-3aaf-4c29-b6ef-b6c1dcba9f5b.png)
![CleanShot 2023-01-22 at 16 44 55@2x](https://user-images.githubusercontent.com/13375294/213936873-1ac79d4d-56e8-4d7d-bbb0-8d91bce838be.png)

**Comment by renatoSouzaAlmeida** [comment]
Problema resolvido
