### ISSUE TITLE
[Detalhes Cliente] Data de Nascimento em Empresa

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#106]
O campo data de nascimento está aparecendo nos detalhes de um cliente tipo Empresa:
![CleanShot 2023-01-22 at 16 48 26@2x](https://user-images.githubusercontent.com/13375294/213937101-b20224ba-780a-46b9-ab5f-f03be57cce81.png)

**Comment by renatoSouzaAlmeida** [comment]
Issue resolvida
