### ISSUE TITLE
[Imóvel] Somatório automático de áreas

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#65]
Remover do primeiro passo do cadastro do imóvel o campo de Área Total, ou seja, não teremos mais o tipo de imóvel e nem o preenchimento de nenhuma área no passo de dados do imóvel;
Remover da edição os campos de área do imóvel;
Os campos de área do imóvel devem ser calculados automaticamente somando as áreas de cada unidade cadastrada;
Nas telas de detalhes do imóvel devemos mostrar as 3 áreas do imóvel, Área Útil, Área Total e Área Habite-se, conforme o somatório das unidades;

**Comment by udyferreira** [comment]
![WhatsApp Image 2022-12-29 at 15 59 05](https://user-images.githubusercontent.com/13375294/210184005-d509bd08-ec7e-4791-9c97-5795b4ae1472.jpeg)

**Comment by cBarbosa** [comment]
@renatoSouzaAlmeida o somatório da área total já está assim, ou seja, ele soma as áreas totais das unidades e apresenta no ímovel. vejo duas coisas que precisa ser feito aqui então.

- remanejar 'área total', 'área util' e 'área habite-se' para o passo "Unidades"
- adicionar 'área 'área util' e 'área habite-se' calculado no topo dos detalhes do imóvel
