### ISSUE TITLE
[Imóvel] Busca do proprietário no cadastro/edição do imóvel deve ser por CPF/CNPJ

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#66]
A buscar do proprietário hoje está sendo realizada por nome, precisamos alterar para buscar por CPF e CNPJ.
![WhatsApp Image 2022-12-29 at 15 21 34](https://user-images.githubusercontent.com/13375294/210184237-afdd1466-994c-4aea-ade1-acda00fa2680.jpeg)

**Comment by cBarbosa** [comment]
@udyferreira vamos aguardar uma posição do UX para propor uma melhor saída para essa pendência.
