### ISSUE TITLE
Desativação de entidades

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#69]
Será necessário ter o conceito de ativo e inativo nas entidades Unidade, Imóvel, Cliente e Fornecedor. Pois precisamos manter o histórico após algum deles deixar de fazer parte da carteira ou do relacionamento com a Iris.

**Comment by cBarbosa** [comment]
@renatoSouzaAlmeida depois avalia isso na modelagem.

**Comment by renatoSouzaAlmeida** [comment]
@udyferreira 
Teremos que incluir um atributo de Status em cada tabela.
Criar um path em cada API para Alteração de Status.

**Comment by renatoSouzaAlmeida** [comment]
ALTER TABLE Imovel ADD Status bit NULL
ALTER TABLE Imovel ADD CONSTRAINT Imovel_STATUS DEFAULT 1 FOR Status	
ALTER TABLE Unidade ADD Status bit NULL
ALTER TABLE Unidade ADD CONSTRAINT Unidade_STATUS DEFAULT 1 FOR Status
ALTER TABLE Cliente ADD CONSTRAINT Cliente_STATUS DEFAULT 1 FOR Status
ALTER TABLE Fornecedor ADD Status bit NULL
ALTER TABLE Fornecedor ADD CONSTRAINT Fornecedor_STATUS DEFAULT 1 FOR Status

UPDATE IMOVEL SET STATUS = 1
UPDATE CLIENTE SET STATUS = 1
UPDATE UNIDADE SET STATUS = 1
UPDATE FORNECEDOR SET STATUS = 1

**Comment by renatoSouzaAlmeida** [comment]
[Inativar Entidades Cliente, Imove e Unidade]
`(https://github.com/cBarbosa/iris-gestao/commit/e0b8bc27e28df3caed1365086a23f03fd70ece7e)```
