### ISSUE TITLE
[Imóvel] Ajuste nos tipos de imóvel

### ISSUE THREAD

**Issue by udyferreira** [cBarbosa/iris-gestao#70]
Os 3 tipos de imóveis devem ser:
_ Edificio Corporativo;
_ Sala/Pavimento;
_ Loja;

**Comment by cBarbosa** [comment]
@udyferreira, atualmente nós temos as seguintes opções na modelagem:
- Edifício Corporativo
- Sala
- Pavimento Corporativo
- Loja Comercial

está correto?

**Comment by udyferreira** [comment]
Não estava vendo a loja na combo. Está lá?Sent from my iPhoneOn 2 Jan 2023, at 15:54, Charles Barbosa ***@***.***> wrote:﻿
@udyferreira, atualmente nós temos as seguintes opções na modelagem:

Edifício Corporativo
Sala
Pavimento Corporativo
Loja Comercial

está correto?
